version: "3.6"
services:
  postgres:
    container_name: ${POSTGRES_HOST:-postgres}
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-default}
      PGDATA: /data/postgres
    volumes:
      - psql-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    restart: unless-stopped
    env_file:
      - ./apps/backend/.env
  backend:
    container_name: ${SERVER_HOST:-qr-backend}
    build:
      dockerfile: Dockerfile.backend
      context: ./
      target: development
    volumes:
      - ./:/usr/src/app
    command: yarn start:dev
    depends_on:
      - postgres
    ports:
      - ${SERVER_PORT:-8000}:8000
    env_file:
      - ./apps/backend/.env
  frontend:
    container_name: ${SERVER_HOST:-qr-frontend}
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Seoul
    env_file:
      - ./apps/frontend/.env

volumes:
  psql-data:
