FROM node:18-slim As production

RUN npm -g install serve
RUN mkdir /app
WORKDIR /app

COPY --chown=node:node ./apps/frontend/package*.json yarn.lock ./

RUN yarn set version berry && yarn

COPY --chown=node:node . .

RUN yarn build:front

EXPOSE 3000

CMD ["serve", "-s", "dist", "-p", "3000"]